spring:
 config:
  import: optional:file:.env-dev.properties
  datasource:
    url:  ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.h2.Driver
  jpa:
   hibernate:
     ddl-auto: update
   show-sql: true
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS}

  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT:6379}



logging:
 level:
   org.springframework.web: DEBUG


management:
    otlp:
      tracing: 
        endpoint:  ${OTLP_ENDPOINT} 
    tracing:
      sampling:
        probability: 1

    endpoints:
      web:
       exposure:
         include: health,info, metrics,env,beans,configprops,heapdump, httpexchanges,loggers,mappings,custom-beans ,prometheus
    endpoint:
       health:
        show-details: always


ai:
  geminiai:
    endpoint: ${AI_GEMINIAI_ENDPOINT:-https://generativelanguage.googleapis.com/v1beta/models/gemini-2.0-flash:generateContent}
    api-key: ${AI_GEMINIAI_API_KEY:-YOUR_API_KEY}




