docspring:
  application:
   name: collectify   

 
  kafka:
   producer:
    value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    key-serializer: org.apache.kafka.common.serialization.StringSerializer
   listener:
      ack-mode: manual


api:
  endpoint:
    base-url: /api/v1

management:
  info:
    build:
      enabled: true
    env:
      enabled: true
    git:
      enabled: true
      mode: full
    java:
      enabled: true
    os:
      enabled: true


info:
  app:
    name: hogwarts-artifact-online
    description: A web application that manages artifacts and wizards for hogwarts school of witchcraft
    version: 0.0.1-snapshot
    author: Shiv

